[package]
name = "prime_rust"
version = "0.1.0"
authors = ["Antoine Demblon <antoine.demblon@student.uclouvain.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miller_rabin = "1.0.6"